---
project_name: govgen

env:
  - GO111MODULE=on

builds:
  - main: ./cmd/govgend
    id: "govgend"
    binary: govgend
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=netgo ledger
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      # .Env.TM_VERSION is provided in the workflow runner environment -> see .github/workflows/release.yml
      - -X github.com/cosmos/cosmos-sdk/version.Name=govgen -X github.com/cosmos/cosmos-sdk/version.AppName=govgend -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.TM_VERSION }} -w -s
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  # disables archiving; to enable use commented lines below
  - format: binary
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  # - format: tar.gz
  #   wrap_in_directory: "true"
  #   format_overrides:
  #     - goos: windows
  #       format: zip
  #   name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  #   files:
  #     - LICENSE
  #     - README.md
  #   rlcp: true

release:
  prerelease: true
  name_template: "v{{.Version}}"

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  skip: false

git:
  # What should be used to sort tags when gathering the current and previous
  # tags if there are more than one tag in the same commit.
  #
  # source: https://goreleaser.com/customization/git/
  tag_sort: -version:refname
  prerelease_suffix: "-rc"
